# Version catalog updates generated at 2026-04-08T12:07:42.434573
#
# Contents of this file will be applied to libs.versions.toml when running versionCatalogApplyUpdates.
#
# Comments will not be applied to the version catalog when updating.
# To prevent a version upgrade, comment out the entry or remove it.
#
[libraries]
# From version 2.11.1 --> 2.11.2
androidx-work-runtime-ktx = "androidx.work:work-runtime-ktx:2.11.2"
# From version 34.10.0 --> 34.11.0
firebase-bom = "com.google.firebase:firebase-bom:34.11.0"
# From version 2.3.10 --> 2.3.20
kotlin-test = "org.jetbrains.kotlin:kotlin-test:2.3.20"
# From version 8.2.0 --> 8.2.2
maps-compose = "com.google.maps.android:maps-compose:8.2.2"
# From version 8.2.0 --> 8.2.2
maps-compose-utils = "com.google.maps.android:maps-compose-utils:8.2.2"
# From version 1.5.0-alpha15 --> 1.5.0-alpha16
material3 = "androidx.compose.material3:material3:1.5.0-alpha16"
# From version 1.10.4 --> 1.10.6
ui-tooling = "androidx.compose.ui:ui-tooling:1.10.6"

[plugins]
# From version 2.3.10 --> 2.3.20
kotlin-android = "org.jetbrains.kotlin.android:2.3.20"
# From version 2.3.10 --> 2.3.20
kotlin-compose = "org.jetbrains.kotlin.plugin.compose:2.3.20"
# From version 2.3.10 --> 2.3.20
kotlin-jvm = "org.jetbrains.kotlin.jvm:2.3.20"
# From version 2.3.10 --> 2.3.20
kotlin-serialization = "org.jetbrains.kotlin.plugin.serialization:2.3.20"
# From version 14.1.0 --> 14.2.0
ktlint = "org.jlleitschuh.gradle.ktlint:14.2.0"
